apiVersion: apps/v1
kind: Deployment
metadata:
  name: btcodechallenge-backend
spec:
  selector:
    matchLabels:
      app: btcodechallenge-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: btcodechallenge-backend
    spec:
      containers:
      - name: btcodechallenge-backend
        image: spring-boot:2.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080